ipDest: 192.168.1.106
videoPort: 1337
audioPort: 1338
ndiSrcName: DESKTOP-G0O595D (wronghousefool)
encoderName: hevc_nvenc
bitrateMbps: 10
gop_size: 1800
max_b_frames: 0
thread_count: 16
xres: 1920
yres: 1080
fps: 60
priv_data:
 preset: llhq
 tier: high
 rc: cbr